### ISSUE TITLE
Перестал работать в Sketch 39.1

### ISSUE THREAD

**Issue by sokos** [dezonik/Typograph#1]
К сожалению, после обновления скетча до Version 39.1 (31720) перестал работать плагин. Переустановка не помогла.

**Comment by dezonik** [comment]
Здравствуйте!

Да, я тоже заметил. Обязательно починю плагин, сам им постоянно пользовался
и теперь вместе с вами страдаю :)
Пока можно юзать Типограф в вебе: http://tpgrf.ru/, типограф Лебедева:
http://www.artlebedev.ru/tools/typograf/ или можно помучаться и настроить
типограф Лебедева в Alfred, чтобы типографить горячей клавишей.

Спасибо, что пользуетесь!

2016-08-02 21:01 GMT+03:00 sokos notifications@github.com:

**Comment by dezonik** [comment]
Fixed!
